[project]
name = "ndl-pyqt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dataclasses>=0.8",
    "pycryptodome>=3.21.0",
    "pyside6>=6.7.3",
    "websockets>=13.1",
]
